### ISSUE TITLE
Obsidian 1.0:  "..." menu is not accessible in Edit mode

### ISSUE THREAD

**Issue by Bluetopia** [valentine195/fantasy-statblocks#102]
When in edit mode in Obsidian 1.0, the "Edit this block" button overlaps the "..." menu action that allows me to add a custom statblock. 

![Overlap_Default](https://user-images.githubusercontent.com/24968231/197344856-701d8c49-5258-4cc8-90bd-ea98e2f1abd5.png)

Minor annoyance right now, but I figured it was worth posting in case it can be easily fixed.  Was not a problem in previous release.

**Workaround:** Use Reading mode which disables the "Edit this block" action so the "..." button is accessible.

**Comment by FilBot3** [comment]
It might also be your Theme you have applied to your Obsidian Vault. Have you tried a different theme?

**Comment by Bluetopia** [comment]
This was specifically reproduced using the Default dark mode theme to confirm the issue, though it is also reproducible in custom themes.  Also tried both normal reading length and extended view just in case and both have the same issues.

**Comment by bszonye** [comment]
I'm seeing the same thing in v1.1.15 of Obsidian, regardless of theme.

**Comment by sigrunixia** [comment]
I am confirming the two buttons still overlap. 

Fix is switching the below from right to left. PR submitted. 

```css
    .icons {
        position: absolute;
        right: 0;
    }
```

**Comment by sigrunixia** [comment]
PR is Merged. Closing.
