### ISSUE TITLE
ASCII for the spaces between names and descs

### ISSUE THREAD

**Issue by DaveZajicek5** [valentine195/fantasy-statblocks#120]
Hi, 
I'm trying to automate transfer from my homebrew monster maker excel to the statblock code format, and I have no idea what symbol is supposed to be those gaps (marked "\_" in the code below):

...
traits:
\_\_-name: "..."
\_\_\_\_desc: "..."
...

It won't appear on regular spaces (ASCII 32) or non-breaking spaces (ASCII 255), so I was wondering whether you know what symbol is required.

Thanks a lot!

D.

**Comment by sigrunixia** [comment]
I know this is a very late reply, but [here are the codes](https://www.rapidtables.com/code/text/ascii/ascii-space.html) for the space key.

Closing this thread. If plugin assistance is needed, a new issue can be created.
