### ISSUE TITLE
Canvas - Encounter Blocks Don't Render

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [valentine195/fantasy-statblocks#122]
Heads up. 

In the new Canvas if you add a card you can successfully render a stat-block however Encounter blocks do not render.

**Comment by valentine195** [comment]
Is this still occurring? it works for me

**Comment by sigrunixia** [comment]
Closing as follow-up response was not given within one month. If this is still an occurrence, a new issue can be created.
