### ISSUE TITLE
json import improvement

### ISSUE THREAD

**Issue by JarradTait** [valentine195/fantasy-statblocks#130]
Hi, when I use the 5etools import button on json's like this

![image](https://user-images.githubusercontent.com/13686225/213963656-d3ffbfbf-1774-417e-a034-44d177e90614.png)

It doesn't bring in the tags anywhere.

![image](https://user-images.githubusercontent.com/13686225/213964063-7980efbe-37c1-42fd-8592-92c1d5254bab.png)

Can monster.type.tags go somewhere so I can query them with dataviewjs?

**Comment by sigrunixia** [comment]
A lot of the tags 5etools uses is for their internal use. They are not actual traits or things that exist on the statblock in official form. A better tool for this function would be Farling's [Obsidian Import Json](https://github.com/farling42/obsidian-import-json) or Ebullient's [TTRPG-CLI](https://github.com/ebullient/ttrpg-convert-cli).
