### ISSUE TITLE
[Bug] Extends function doesn't seem to be working

### ISSUE THREAD

**Issue by Pachtjuilaard** [valentine195/fantasy-statblocks#133]
Hi!

I'm trying to create a creature template, to slap onto existing creatures using the `extends` function, but it doesn't seem to be working.

For example, I have this statblock:
```statblock
monster: Goblin
name: Barry
extends: Archmage
```

It only show the statblock for a Goblin named Barry. No Archmage abilities there. An Archmage named Barry with `extends: Goblin` also doesn't have Nimble Escape or a scimitar.

**Comment by sigrunixia** [comment]
Closing as this was indeed fixed!
