### ISSUE TITLE
Menu not disappearing when creating custom layout

### ISSUE THREAD

**Issue by Dakkon77Blackblade** [valentine195/fantasy-statblocks#141]
To begin with: Thanks for the great work!

I am currently creating a custom layout for "The Dark Eye" RPG. While doing so I ran into the issue of never disappearing menus. Whenever I add an object to the layout the submenu stays on screen. Only fix seems to be restarting Obsidian.

Confirmed the bug in new vault in version 1.1.9 with only TTRPG Statsblock installed via community addons.

![custom-layout-menu-bug](https://user-images.githubusercontent.com/125127583/218254625-36c9569e-0a3e-4950-8501-b9ecf62702ce.jpg)

**Comment by Dakkon77Blackblade** [comment]
Update: This issue seems only to exist for wide screen resolutions. I tried the same on my second screen (2560x1440) without any trouble. On the primary screen (3440x1440) the menus stay visible. 
Very strange behavior... still nice to have this workaround using the smaller display for editing the layout.

**Comment by Dakkon77Blackblade** [comment]
Update: Unfortunately I need to correct myself. Same issue reappeared on the 2560x1440 Screen. This was on Windows 11. Moved to a Linux Mint machine, fresh install of Obsidian via Flatpack, same behavior on full HD display. So seems to be more general type of display bug.

**Comment by valentine195** [comment]
Is this still an issue?

**Comment by sigrunixia** [comment]
Closing as one month has passed without reply. If assistance is still needed, a new issue can be created referencing this one.
