### ISSUE TITLE
MD Spell Link Escaping breaks spell list formatting

### ISSUE THREAD

**Issue by jshank** [valentine195/fantasy-statblocks#142]
Adding MD links to spells causes them to render incorrectly. I'm using frontmatter `statblock: true` and seeing the following

![image](https://user-images.githubusercontent.com/515808/218372039-41075d05-a129-48ad-bdbc-f14c2a4a5b32.png)

- Obsidian 1.1.9
- TTRPG Statblocks 2.24.22
- ITS Theme 0.8.87 (alternate SlRvb D&D

```
spells:
  - "The wizard is a 9th-level spellcaster. His spellcasting ability is Intelligence (spell save DC 14, +6 to hit with spell attacks). The spellcaster has the following wizard spells prepared:"
  - "Cantrips (at will): [[fire bolt]], [[light]], [[mage hand]], [[prestidigitation]]"
  - "1st level (4 slots): [[detect magic]], [[mage armor]], [[magic missile]], [[shield]]"
  - "2nd level (3 slots): [[misty step]], [[suggestion]]"
  - "3rd level (3 slots): [[counterspell]], [[fireball]], [[fly]]"
  - "4th level (3 slots): [[greater invisibility]], [[ice storm]]"
  - "5th level (1 slot): [[cone of cold]]"
```

I've tried the recommendation from #24 and it still renders incorrectly.

**Comment by sigrunixia** [comment]
Closing as this should be fixed. If this is still an issue, a new thread will be needed.
