### ISSUE TITLE
No styling or preferences

### ISSUE THREAD

**Issue by Urethramancer** [valentine195/fantasy-statblocks#144]
I just installed Obsidian and this plugin for the first time (about an hour ago), but I'm not getting styled previews or a settings section for the plugin. I've tried making it the only enabled plugin without any change there.

![bug](https://user-images.githubusercontent.com/2459910/218580949-5fd9544a-b478-48a3-a43c-21cf95878fe7.gif)
![mia](https://user-images.githubusercontent.com/2459910/218582087-7bced4d0-0194-468a-b5f4-b2fa3d306cfd.jpg)

Obsidian version: 1.1.9
Fantasy Statblocks: 2.25.0
OS: macOS Ventura 13.x

What could be wrong? Is there some setting in Obsidian I've missed?

**Comment by valentine195** [comment]
Hey sorry, you caught a little bug that could prevent the plugin from loading its settings tab when being installed. I just pushed a fix... please try updating.

**Comment by Urethramancer** [comment]
Cheers, all looking good now :)
