### ISSUE TITLE
DndAppfiles bestiaries do not pick up action texts

### ISSUE THREAD

**Issue by rune-bk** [valentine195/fantasy-statblocks#15]
When importing any bestiary from DnDAppFiles I get the action names, but not the descriptive text to go with them. It exists in the XML.
For example from Adult Black Dragon:
`<action>
<name>Multiattack</name>
<text>
The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws.
</text>
</action>`
Here is what is shown. The action list continues on the next column but without any descriptive text.
<img width="161" alt="Screenshot 2021-11-20 at 17 28 02" src="https://user-images.githubusercontent.com/996032/142733782-b022650f-fa16-46a1-925c-7cc02e6916d2.png">

The same applies to legendary actions

**Comment by valentine195** [comment]
Sorry about that, this will be fixed in version 2.0.0

**Comment by VacantSoul** [comment]
Sadly not working on the latest update :) but i may just be to eager as a load of updates seem to have been pushed

**Comment by valentine195** [comment]
You can install the v2.0.0 beta through the Obsidian BRAT plugin. This fix should be done on that branch. I just want to give it a few days to see if any bugs come in before pushing that to live.

**Comment by VacantSoul** [comment]
ah ok, i tried that the other day and it would not enable within obsidian. I will give it another try now, thanks.

**Comment by VacantSoul** [comment]
ah, i see what i did wrong now! thank you again

**Comment by valentine195** [comment]
Is it always duplicating?

**Comment by VacantSoul** [comment]
Just tried it on a Vault that had never used the plugin before, it does seem to be every time and every trait and ability 
![image](https://user-images.githubusercontent.com/71190575/146435425-3de82fa1-384c-400e-bbc3-3fc0980e7111.png)

**Comment by VacantSoul** [comment]
I tried a couple of sources too

**Comment by valentine195** [comment]
No worries, was an error on my end. Should be fixed in the latest beta.

**Comment by VacantSoul** [comment]
Awesome, i'll check it out shortly.
________________________________

**Comment by VacantSoul** [comment]
No more duplications, did take a look at a dragon and it seems to be missing lair and regional details for the next iteration 👍 
![image](https://user-images.githubusercontent.com/71190575/146443678-167da6c1-c103-475d-a5ac-801bcf841f2b.png)

**Comment by sigrunixia** [comment]
Closing as this appears to be adequately fixed. If not, a new issue can be created.
