### ISSUE TITLE
5E Stat Block not showing Traits/Actions if custom Traits/Actions added

### ISSUE THREAD

**Issue by PaganApe** [valentine195/fantasy-statblocks#156]
It appears that if you customise an existing monster stat block by adding a custom Trait or Action then it no longer shows any of the Traits/Actions from the source monster.

For example

```statblock
monster: Elvish Veteran Archer
name: Zeno Windrider
traits:
    - [Description, Wears studded leather armour. Has Dexterity AC bonus]
```

would show only the specified **Description** trait, and not, for example, the **Fey Ancestry** trait that the "Elvish Veteran Archer" has.

**Comment by PaganApe** [comment]
Just for clarity, things like **Languages**, **Skills** and **Armor Class** are being displayed as expected, so at least some of the attributes from the source monster are being brought in correctly.

**Comment by sigrunixia** [comment]
Hi @PaganApe 

If you are still having issues, can you please post your entire statblock code block you are using, as well as a screenshot of what does display?

**Comment by PaganApe** [comment]
So, as an example of the behaviour, if I bring in a standard Orc monster it looks like this:

![image](https://user-images.githubusercontent.com/129972974/231713003-abe19d66-d515-46bf-a9b2-d9cc6de5477d.png)

![image](https://user-images.githubusercontent.com/129972974/231713342-c87d4922-c4fe-47d8-8b61-967b91acf726.png)

But if I name an Orc and give him a custom trait, then it overwrites the **Aggressive** trait of the standard Orc and just displays my custom trait, in this example **Description**. Previously it would just add my custom trait to the base creature's traits.

![image](https://user-images.githubusercontent.com/129972974/231713720-ef22297a-b809-4866-9aba-554ab08e0a35.png)

![image](https://user-images.githubusercontent.com/129972974/231714677-1ea84300-688e-41e4-82bd-8012573a44b6.png)

This happens regardless of which monster I choose as the base creature, and also happens with Actions, so any custom Action will overwrite any Actions the original base creature has.

**Comment by valentine195** [comment]
@sigrunixia the plugin has always replaced Trait arrays if specified in a monster. Syntax for making it additive can get a little wonky… maybe the plugin can look for `trait_key+` in addition to `trait_key`

**Comment by PaganApe** [comment]
> @sigrunixia the plugin has always replaced Trait arrays if specified in a monster. Syntax for making it additive can get a little wonky… maybe the plugin can look for `trait_key+` in addition to `trait_key`

In the past, I've seen the plugin replace a Trait if you supply your own with the same name, but it's only recently that the whole Trait and Action sections are replaced if you provide a Trait or Action section of your own. A lot of my NPCs were created this way, using a base Monster and then naming and tweaking it to make it unique. If I check back through my NPCs they have now all lost the Traits and Actions that previously came through from the base monster.

**Comment by PaganApe** [comment]
Perfect, thank you for the prompt response.
