### ISSUE TITLE
Allowing bold and italics within the stat block

### ISSUE THREAD

**Issue by mohitmax** [valentine195/fantasy-statblocks#16]
First of all, thank you for creating this. This is pretty awesome tool. 

I have a request:
On adding Actions, like below, the "Ranged Spell Attack" is normally italicized. Can this be added?

[Ray of Frost, Ranged Spell Attack: +4 to hit, range 60 ft., one creature. _Hit:_ 4 (1d8) cold damage, and the target’s speed is reduced by 10 feet until the start of the gnome’s next turn.]

**Comment by valentine195** [comment]
This is now possible in the latest beta.

**Comment by stevenoftheages** [comment]
In the beta, how do we do it? Underscores?

**Comment by sigrunixia** [comment]
The line break is controlled by whether or not the name of the trait and the text of the trait are rendered in the same container. Some themes and snippets separate out the two.

Documentation on how to control either one will be coming shortly. :)

**Comment by adamhp** [comment]
It's still not entirely clear how to use either bold or italics within text of the statblock. I've tried to find it in the docs with no luck. Any suggestions? @sigrunixia
