### ISSUE TITLE
Allow for manually specifying the proficiency bonus

### ISSUE THREAD

**Issue by bfad** [valentine195/fantasy-statblocks#39]
I have tried to manually specify the proficiency bonus using the `proficiency_bonus` key in the stat block, but it looks like it's always set to be calculated from the CR. The problem is that for summoned creatures, the proficiency bonus is often equal to the castors or occasionally based on the level the spell was cast at. It would be nice to be able to specify that and have it show up like it does in the stat block of my source book.

Ex:
<img width="149" alt="image" src="https://user-images.githubusercontent.com/379467/154176326-a8ee430e-8086-48fa-b0bf-eeb71357e536.png">

**Comment by bfad** [comment]
I'm not entirely certain how `modifier` is meant to be used, but I did try these different combinations to no affect:
```
modifier: equals your castor level
```

```
modifier:
  proficiency_bonus: equals your castor level
```

```
proficiency_bonus:
  modifier: equals your castor level
```

I did this at the root and `trait` level (`action` doesn't really make sense), but it didn't work.

**Comment by sigrunixia** [comment]
This has been implemented by default in 5e. You can now modify the proficiency bonus (thus modifier) by editing the Basic 5e Layout -> Proficiency Bonuses -> Dice Callback Section.
