### ISSUE TITLE
Do Actions/Traits support bullet points?

### ISSUE THREAD

**Issue by matt-evangelidis** [valentine195/fantasy-statblocks#5]
Hi, Jeremy

Really enjoying this tool so far, but quick question: do the actions/traits sections support bullet points? I can see that the spellcasting section does.

**Comment by valentine195** [comment]
Let me think on it, should be possible. The syntax is already pretty ugly and I don't want to make it uglier 😁

**Comment by sigrunixia** [comment]
Closed as Traits support bullets best through `<ul>`.
