### ISSUE TITLE
improving the layout editor

### ISSUE THREAD

**Issue by dsimonow** [valentine195/fantasy-statblocks#50]
Love that it is possible to create layouts. I am currently trying to make a pathfinder2e statblock layout.

The problem is, when dealing with a complex layout and moving stuff around in there the boxes will constantly resize and basically move the drop point because of that.
Making them only resize after dropping it off would improve the experience or make the blocks moveable by arrow keys so we can just navigate to the proper place.

thank you!

**Comment by sigrunixia** [comment]
Would you say this is done enough, @valentine195, or is there room for improvement within the bounds of the request?

**Comment by valentine195** [comment]
There is probably still room for improvement but I'm using an underlying library for this so it's unlikely much can be changed without rolling my own.

**Comment by sigrunixia** [comment]
Since improving the layout editor further past what has been done would also then be included in a hefty rewrite, I'll go ahead and close this older request then. It's still in on the table as far as future outlooks.
