### ISSUE TITLE
Feature Request: Template String Notation Block

### ISSUE THREAD

**Issue by Oudwins** [valentine195/fantasy-statblocks#53]
This would be very useful for create complex custom layouts. Because it would allow us to run JS to format the data on view.

For example, one could take the normal stats and print only the modifiers without even printing the keys.

A rudimentary version of this should not be difficult to implement. Ideally one could write the template syntax with common readable variable names like such:

`${ac} | ${hp}`

But that might be a little more difficult than just taking the implementation of subheading and using that as such

`${subheading[0]} | ${subheading[1]}`

Im not familiar at all with svelte and still learning TS. So im worried im gona break something I don't understand. But on the render side something like this should work right?

```ts
<script lang="ts">
    import type { Monster } from "@types";
    import type { StringTemplateItem } from "src/data/constants";
    import { stringify } from "src/util/util";

    export let monster: Monster;
    export let item: StringTemplateItem;
    const templateItems: string[] = [];

    for (let property of item.properties) {
        if (property in monster) {
            templateItems.push(`${stringify(monster[property])}`);
        }
    }
    // it would have access to templateItems
    const text = new Function("return " + item.templateString + " ").call(item.templateString);
</script>

{#if templateItems.length}
    <div class="subheading">
        {text}
    </div>
{/if}
```

**Comment by Oudwins** [comment]
You are totally right. I missed that you could do this somehow. Thanks.

**Comment by Oudwins** [comment]
Up on further testing. Any particular reason as to why it is not posible to specify a callback for other blocks a part from the property block? For example the heading block

**Comment by sigrunixia** [comment]
Hello @Oudwins. 
I am not sure if you are still using Statblocks, but I wanted to make sure you were aware of

**Comment by Oudwins** [comment]
> Hello @Oudwins. 
> I am not sure if you are still using Statblocks, but I wanted to make sure you were aware of the update that added the Javascript Block to layout. The Javascript block has access to the global JS within Obsidian, so this may be able to accomplish what you need.



Thank you! I'll try to check it out this week. I finished my DnD campaign few months ago and have been on a break since.

**Comment by sigrunixia** [comment]
Awesome! @Oudwins.

I'll leave this open. Please us know how it works out and if it does not quite hit the mark, we can look at how it can be tweaked. There's much more from both @valentine195 and I in expanding what Javascript capabilities Statblocks can do, now than there was last year, much of it due to technology. 

Alternatively, if it does do what you need to do, I'd love to see how you used it. It's quite an intimidating block for some users so I don't get to see the results of it much! :)

**Comment by valentine195** [comment]
I will consider this closed, the JS block is much more powerful than a template notation block.
