### ISSUE TITLE
Feature request: dice roller block

### ISSUE THREAD

**Issue by lolbat** [valentine195/fantasy-statblocks#68]
It would be awesome to be able to directly add a link to a dice roller in a stat block. There are quite a few OSR monsters that have random features. For instance the Beastmen in DCC have a randm mutation. I've built a table to determine what that is but I currently can't put it in a stat block unless I write JS code.

**Comment by sigrunixia** [comment]
Hello!

To clarify, are you asking for a specific Dice Roller layout block, similar to how there are trait and property blocks, that would allow you to customize dice calls?

**Comment by sigrunixia** [comment]
Closing. If this feature request is desired, a new issue can be created.
