### ISSUE TITLE
Feature request: Import mobs from .md files

### ISSUE THREAD

**Issue by f3ss1** [valentine195/fantasy-statblocks#74]
Hey there!

I really appreciate your work.

I did make a whole bunch of homebrew mobs via creating the pages of them (you know that ```statblock ..) and now I realise that I need to transfer all of them manually to the plugin using the "add creature" button in order for the plugin to work with the initiative tracker, for example.

This really upsets me and of course I am not doing that by hand so I am losing a big part of synergy here. Is it possible for you to make some workaround for this?

Huge thanks in advance!

**Comment by sigrunixia** [comment]
Adding to this before I close, this is also included as a part of the `statblock: inline` function that was added a short while ago.
