### ISSUE TITLE
Whitespace added before checkmarks

### ISSUE THREAD

**Issue by kylomax** [valentine195/fantasy-statblocks#80]
When creating a Markdown with "- [ ] " for instance, the checkmark is added on a new line. The checkmark fully works though (render as markdown is enabled). I am attempting to use this to track inspiration. Here are a few screenshots. If I do a normal checkmark like this:
![statblock normal checkmark](https://user-images.githubusercontent.com/77210114/183951297-5565deb1-df39-4b6e-8d3e-32002c2eea01.png)

it renders like this:
![rendering normal checkmark](https://user-images.githubusercontent.com/77210114/183954311-9f065d4a-8348-465c-a5cc-505dafab9596.png)

If I remove the dash before, it renders on the same line but not as a checkmark
![inspiraiton](https://user-images.githubusercontent.com/77210114/183954476-af36bff1-e58b-4694-b2f0-f6cb05a0d22e.png)

Currently I am using a text block instead of a property block and making the checkmark like this:
![inspiration](https://user-images.githubusercontent.com/77210114/183954634-c4a5f966-d177-4c88-9aca-5a17b0ff8ab5.png)
![workaround](https://user-images.githubusercontent.com/77210114/183954660-e81ea9e8-fdf6-4b01-bedd-00425c49d156.png)

The problem with this is it still has whitespace above.

**Comment by sigrunixia** [comment]
Hi @kylomax 

Can you check if this is still occurring on your end?

**Comment by sigrunixia** [comment]
Thanks. Added to the bug-to-do list. <3

**Comment by valentine195** [comment]
@kylomax this is because `<ul>` elements by default have margins + block display set by the browser.

I would prefer not to override this globally... it could break a lot more than it is worth, I think.

You can fix it pretty simply:

```css
.statblock-markdown ul {
    margin: 0;
    display: inline-block;
}
```

That will hit all `<ul>` elements being rendered as markdown within a stat block.

You could target just inspiration as well:
`.statblock .inspiration ul ...`
