### ISSUE TITLE
Can't override hp with Dice roller integrated

### ISSUE THREAD

**Issue by irrevenant** [valentine195/fantasy-statblocks#87]
I'd expect the following to give me a stat block for a Nightmare with 40 hit points, but it always gives me the average for the hit dice.

````
```statblock
monster: Nightmare
hp: 40
```
````
I assume there is something I could do in the callback to fix this myself, but I haven't been able to play around with that yet, and it does seems like a bug?

TTRPG Statblocks v2.16.2
Dice Roller v8.6.4

**Comment by danstreeter** [comment]
I've also noticed that when _not_ using an existing stat block and defining your own, the simple `hp: 32` renders with a dice roll icon and brackets as if it were a roll.
When clicking the dice to perform a roll with a static value - there are errors in the console.
Changing to `hp: 1d20` you get the same output, but a functioning roller.

It seems that the `hp:` field is defaulting to a roller?

**Comment by sigrunixia** [comment]
Closing as this appears resolved by Kylo.
