### ISSUE TITLE
Specifying `monster` in frontmatter doesn't seem to have any effect

### ISSUE THREAD

**Issue by alwaysblank** [valentine195/fantasy-statblocks#99]
If I define some frontmatter like so:

```
---
statblock: true
monster: Changeling
name: Alfred
---
```
And then reference it inline:

````
```statblock
monster: Alfred
```
````

It renders as:

![Screen Shot 2022-10-12 at 7 12 12 PM](https://user-images.githubusercontent.com/23412884/195482768-af5ea21b-a21e-4d4b-a6f7-626d3da2b5fd.png)

My expectation would be that it would show me the stat block for the Changeling, but it would have the name "Alfred" instead of "Changeling."

If I do the same thing inline:

````
```statblock
monster: Changeling
name: Alfred
```
````

Then it renders as expected:

![Screen Shot 2022-10-12 at 7 13 02 PM](https://user-images.githubusercontent.com/23412884/195482875-498a652f-7382-46ef-898a-715f09a9fe03.png)

I've tried messing around with bestiary settings, but that doesn't seem to be the issue. "Changeling" is a a custom monster I entered manually, but the same behavior occurs if I use monster that ship with the plugin.

**Comment by alwaysblank** [comment]
I'd be happy to take a look at fixing this one myself if someone can point me at the area of the codebase where this merge gets resolved. I dug around a little bit but couldn't find an obviously smoking gun.

**Comment by znewton** [comment]
@alwaysblank I was trying to look into how to fix this as well. In doing so, though, I found a workaround! You can use the [Extending](https://github.com/valentine195/obsidian-5e-statblocks#extending) feature to accomplish the same thing, and it works with Frontmatter.

```md
---
statblock: true
name: TestCreature
extends:
 - Goblin
---

\```statblock
creature: TestCreature
\```
```
(ignore the \ in front of the statblock, just for GitHub formatting/viewing)

The above seems to work as expected
![image](https://user-images.githubusercontent.com/14362200/205364924-c33b55cd-a4f9-4f8d-b35e-71c80692c8bb.png)
![image](https://user-images.githubusercontent.com/14362200/205364946-216cddeb-712b-4b69-8b86-4f6b3a539800.png)

**Comment by sigrunixia** [comment]
`monster:` is specifically meant to call a named entity out of the bestiary. Znewton's method is the official way front matter versions should be handled. 

We probably ought to make it a protected key to keep this from happening. Adding as an enhancement.

**Comment by valentine195** [comment]
Hi, yes, please use `extends` for front matter.
